export const HomeActions = {
  CRAWL: 'CRAWL',
  CHANGE_FORM_FIELD: 'CHANGE_FORM_FIELD',
  CHANGE_TERMS: 'CHANGE_TERMS',
  SET_FORM_FRAME: 'SET_FORM_FRAME',
  SET_PROCESSING_FRAME: 'SET_PROCESSING_FRAME',
  SET_RESULTS_FRAME: 'SET_RESULTS_FRAME',
  CLEAR_FORM: 'CLEAR_FORM',
  SET_RESPONSE_ERROR: 'SET_RESPONSE_ERROR',
  CLEAR_RESPONSE_ERROR: 'CLEAR_RESPONSE_ERROR'
}
